### ISSUE TITLE
BUG Report

### ISSUE THREAD

**Issue by OshinoMuse** [MDMods/Cinema#2]
version 1.2.0
bug: when the original backgroud get entirely dark(like the beginning of INTERNET YAMERO), **_the video will be dark too._**
in the custom chart アイドル
_**about 222 combo, the background get dark, but if i add a video, the video will disappear during this part.**_
i send a bug demonstrating and the chart, hope it will help.
Hope this bug can be fix in the future version, thank you!

[アイドル.zip](https://github.com/MDMods/Cinema/files/14375369/default.zip) (the video is too big to be allowed to upload)

https://github.com/MDMods/Cinema/assets/160872483/87e304a5-bdf0-4935-9fbf-24cd6d884cdc

**Comment by OshinoMuse** [comment]
This one includes video
[アイドル(mv ver.).zip](https://github.com/MDMods/Cinema/files/14375887/mv.ver.zip)

**Comment by ALLMarvelous** [comment]
You use the Hide Background (iBMS ID 25) object here, which hides the background. This object hides the background video since the background is already concealed by the cinema video. If you are wanting to not hide the background video, remove the Hide Background element.
